baseURL = 'https://tano-shiina.com/'
title = 'たのしいな。'
theme = 'PaperMod'
locale = 'ja'

[params]
  env = "production"
  defaultTheme = "auto"
  description = "たのしい。本や映画や日々考えたことについての個人的なログがあつまっている。"
  ShowReadingTime = false
  ShowShareButtons = true
  ShareButtons = ["x", "facebook", "line", "hatena", "bluesky"]
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  disableScrollToTop = false
  ShowToc = true
  TocOpen = true
  DateFormat = "2006/01/02"

[params.homeInfoParams]
  Title = "👻 Kibi Shiina's Website 😱"
  Content =  """
「たのしいな。」は、吉備椎菜の個人サイトです。     
ヒトがつくったものと、ヒトがつくっていないものについてよく書く。  
げんざい整備中 (2026-09～) 
"""

[[params.socialIcons]]
  name = "x"
  url = "https://x.com/アカウント名"

[params.cover]
  hidden = false
  hiddenInList = false
  hiddenInSingle = false
  responsiveImages = true
  linkFullImages = false

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  limit = 10
  keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 5

[[menu.main]]
  name = "Archives"
  url = "/archives/"
  weight = 10

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 15

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 20

[[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 30

[markup.goldmark.renderer]
  unsafe = true
  hardWraps = true

[permalinks]
  posts = "/:year/:month/:day/:slug/"
